language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: QlE/vda76QEdyZPmtfyXsZRnUAozKTn57juMA1LPZXhMRpwiMtlHQI3uvugQpF6TgE7LoMNDcrjzhLU8CLia/Dzbb5FV5sBBrH68iSUDni5vGqCuaBpQQBJM5fZQcUdY7PGl0KkknkhxvaPlRJ9wpTiPGrIQ0zxrKo+j/BiBknpZ0OFYOlgDPcLyXj1S/su5s/PUeR7Zq/rGZu23j7z6dTWSok+jNYbR9eZ2RkgSyHB3Jwdzl1+zAwu1JLRG0AfVyKBOEIQ0AwSj1PgWfqrNjIbNuDQXKuDGj99M3dYKtHCII5d/ev3k8t7UnRNM5AQvjilASvpdhORkKEA7Csq6lJt+tG5x64VpkLjZ6MU/1MUELeFXQIT7PPaAM3Blbi5PvUo9Sgvu4yg7Stdu38oy6KgKMIUinU036ACcL7YYTyCx2hlIU4NMzADRylt5Egk6v8WMO3ZYslezZjZR3QwY//nkGWBJ5QibBiW97WqKSj3SU12TXSM9xar34axQjpO6l8kGEx9BTF2JV/XeEGXYCUnzwvbjHDH7uB4NjPUiyJCXbqqAqMv0LXZPxO2vnGPcZZwowivUgE5PGTXgU8ge9nWXAC8LzG52SXDKuqf4wC6X84ntlyjsbszxoPPYB5/32MjZGoXnBRgKyPyH64Hw+q9jCcGi/qyrJzuujAjNgyU=
  - secure: mBjko20JVSb09V2uahm9rONK3zuiBtUu6jrR1oCV9Um2l298vOld0hwfyAACNLLVc7nF8aDsDehDafddApvRrldpH60Hdh7MhvP2zu2jaBLRHP1TKw48M8p43n0ELNkOr6f+34pZ/lOn4nph8FT4JZOH+FQfV13NnhICw8If4XOe31E1jMrk/vbQPAauKrkD+fOA8NWnPlxEWDVhlEVZTItFdeN9KQhuD2FjDRX7Vt5JN321JmwGVPakeoVz1CXN+NyyE2rlscFIlxtwOhvQe8OC9tWezmTDh8zRgSq5cL6N7PAd+a/chj6RvZXxMMGUkMI0CrwoxBW0jzUisL831N5Cal5nJPh0MEUvZoxKg/zRvqGmQv8ZlFKoV23zemI+Zp1dfrFmPHU3OxsOqAZC+mjKYGORgmXz3FZEeefzxBPqGZuZrVtnZ7To9bDmpaJ3TwlewlZW0UovJuNfCpsnuiTJMcgZlLGQcqRXuRK92iw/17fr1Y/rIHFGsyNR5aZ2ONv0DPIzsYS8UQLgzAquHpIuk+Q9k+W42uVZpsiv1IQcYIQ9i3dNHJPv7k/cWfwUS50RkMqmjUOx/uSfhYAd6Iit7PWE9fpk9WsicDjDGmZZmbKS0n31hSxhOPPtJaeyacbwAhTHKnAJLoZ840jT9HoJvwUME7t8LSmp3OBNp28=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
